sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
language: node_js
node_js:
  - "stable"
  - "--lts"
before_script:
  - git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
  - git fetch origin master
after_success:
  - "npm run coveralls"
