sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libssl-dev
      - gcc-4.9-multilib
      - g++-4.9-multilib
language: node_js
node_js:
  - "stable"
  - "6"
after_success:
  - "npm run coveralls"
